# =============================================================
#                 DEPLOYMENT
# ==============================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80

#kubectl get rs
#kubectl delete rs XXXXX
#kubectl delete -f deployment.yml
#kubectl delete deployment XXXX
# kubectl delete -f deployment.yml
#kubectl scale --replicas=6 -f deployment.yaml   ## Scale up
#kubectl scale --replicas=1 -f deployment.yaml ## Scale down